run:
  timeout: 10m
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - godot
    - goimports
    - bodyclose
    - sqlclosecheck
    - rowserrcheck
